package dyuque;

import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * Runs the Dyuque chatbot application and coordinates command execution.
 */
public class Dyuque {
    /** Default path used to store saved tasks. */
    private static final Path SAVE_PATH = Path.of("dyuque_data", "dyuque.txt");

    /** Parser component responsible for converting user input into commands. */
    private final Parser parser;
    /** In-memory list of tasks managed by the chatbot. */
    private final TaskList taskList;
    /** Stack of UndoActions to support undo command */
    private final Deque<UndoAction> undoStack = new ArrayDeque<>();
    /** Whether a new savefile was created during startup */
    private final String savefileCreatedNotice;
    /** Whether the main chat loop should stop executing. */
    private boolean executionShouldStop;

    /**
     * Represents the supported commands and their accepted keywords.
     */
    protected enum Command {
        HELP("help",
                "help"),
        LIST("list",
                "list", "ls"),
        FIND("find <keyword>",
                "find", "f"),
        TODO("todo <description>",
                "todo", "t"),
        DEADLINE("deadline <description> /by <date>",
                "deadline", "d"),
        EVENT("event <description> /from <date> /to <date>",
                "event", "e"),
        DELETE("delete <index>",
                "delete", "remove", "rm"),
        MARK("mark <index>",
                "mark", "m"),
        UNMARK("unmark <index>",
                "unmark", "um"),
        UNDO("undo",
                "undo"),
        EXIT("exit",
                "bye", "exit");

        /** User-facing help string to use the command. */
        private final String usageHelpStr;

        /** Keywords that map to this command. */
        private final Set<String> keywords;

        Command(String usageHelpStr, String... keywords) {
            this.usageHelpStr = usageHelpStr;
            this.keywords = Set.of(keywords);
        }

        /**
         * Returns the user-facing string explaining the command syntax.
         *
         * @return String explaining the command syntax.
         */
        public String getUsageHelpStr() {
            return "Usage: " + usageHelpStr;
        }

        /**
         * Returns the command matching the specified keyword, if any.
         *
         * @param keyword Keyword to resolve into a command.
         * @return Matching command if the keyword is recognized.
         */
        protected static Optional<Command> getCommand(String keyword) {
            for (Command command : values()) {
                if (command.keywords.contains(keyword)) {
                    return Optional.of((command));
                }
            }
            return Optional.empty();
        }
    }

    @FunctionalInterface
    private interface UndoAction {
        String undo() throws DyuqueException;
    }

    /** Package-private constructor for test classes */
    Dyuque(Parser parser, TaskList taskList, String savefileCreatedNotice) {
        this.parser = parser;
        this.taskList = taskList;
        this.savefileCreatedNotice = savefileCreatedNotice;
        this.executionShouldStop = false;
    }

    /**
     * Creates a Dyuque instance configured with default UI, storage, parser, and task list.
     *
     * @return A fully initialized Dyuque instance.
     * @throws DyuqueException If saved tasks cannot be loaded.
     */
    static Dyuque initialiseDefaults() throws DyuqueException {
        Parser parser = new Parser();
        Storage storage = new Storage(SAVE_PATH);

        Storage.SavefileResult result = storage.load();
        TaskList taskList = new TaskList(result.tasks(), storage);

        String savefileCreatedNotice = result.wasNewFileCreated()
                ? "No save file found. Created a new one at:\n  " + SAVE_PATH
                : "";

        return new Dyuque(parser, taskList, savefileCreatedNotice);
    }

    /**
     * Processes user input and returns the response message for display.
     *
     * @param input Raw user input line.
     * @return The user-facing response message.
     * @throws DyuqueException If the input cannot be parsed or the command fails to execute.
     */
    public String getResponse(String input) throws DyuqueException {
        CommandArgumentPair pair = parser.parseCommand(input);
        return executeCommand(pair);
    }

    /**
     * Executes the parsed command and returns the result message.
     *
     * @param pair The parsed command and arguments.
     * @return The user-facing output String generated by the executed command.
     * @throws DyuqueException If the command fails to execute.
     */
    String executeCommand(CommandArgumentPair pair) throws DyuqueException {
        Command command = pair.command();
        assert command != null : "Parser returned null command";

        String[] arguments = pair.argument();
        assert arguments != null : "Parser returned null arguments";
        /*  Elements of arguments:
                delete/mark/unmark: index
                to-do:              description
                deadline:           description, dueDate
                event:              description, fromDate, toDate
         */

        return switch (command) {
            case HELP -> handleHelp();
            case LIST -> handleList();
            case FIND -> handleFind(arguments[0]);

            case TODO -> handleAddTask(new Todo(arguments[0]));
            case DEADLINE -> handleAddTask(new Deadline(arguments[0], arguments[1]));
            case EVENT -> handleAddTask(new Event(arguments[0], arguments[1], arguments[2]));

            case DELETE -> handleDeleteTask(arguments[0]);

            case MARK -> handleMarkTask(arguments[0]);
            case UNMARK -> handleUnmarkTask(arguments[0]);

            case UNDO -> handleUndo();

            case EXIT -> handleExit();
        };
    }

    private String handleHelp() {
        return Ui.showHelp();
    }

    private String handleList() {
        List<Task> allTasks = taskList.getAllTasks();
        return Ui.formatTaskList(allTasks, false);
    }

    private String handleFind(String keyword) {
        List<Task> matchingTasks = taskList.find(keyword);
        return Ui.formatTaskList(matchingTasks, true);
    }

    private String handleAddTask(Task task) throws DyuqueException {
        Task addedTask = taskList.add(task);
        int addedIndex = taskList.size() - 1;

        undoStack.push(() -> {
            Task deletedTask = taskList.delete(addedIndex);
            return Ui.formatTaskDeleted(deletedTask, taskList.size());
        });

        return Ui.formatTaskAdded(addedTask, taskList.size());
    }

    private String handleDeleteTask(String indexStr) throws DyuqueException {
        int index = parseTaskIndex(indexStr);
        Task deletedTask = taskList.delete(index);

        undoStack.push(() -> {
            taskList.add(index, deletedTask);
            return Ui.formatTaskAdded(deletedTask, taskList.size());
        });

        return Ui.formatTaskDeleted(deletedTask, taskList.size());
    }

    private String handleMarkTask(String indexStr) throws DyuqueException {
        return processStateChange(indexStr, Task.State.MARKED);
    }

    private String handleUnmarkTask(String indexStr) throws DyuqueException {
        return processStateChange(indexStr, Task.State.UNMARKED);
    }

    private String processStateChange(String indexStr, Task.State newState) throws DyuqueException {
        int index = parseTaskIndex(indexStr);
        Task.State previousTaskState = taskList.getTaskState(index);

        Task updatedTask = taskList.setMarkedState(newState, index);

        undoStack.push(() -> {
            Task restoredTask = taskList.setMarkedState(previousTaskState, index);
            return Ui.formatTaskChangedState(restoredTask, previousTaskState);
        });

        return Ui.formatTaskChangedState(updatedTask, newState);
    }

    private String handleUndo() throws DyuqueException {
        if (undoStack.isEmpty()) {
            return Ui.showError("Nothing to undo.");
        }
        return undoStack.pop().undo();
    }

    private String handleExit() {
        requestStop();
        return Ui.showGoodbye();
    }

    private int parseTaskIndex(String indexStr) throws DyuqueException {
        try {
            return Integer.parseInt(indexStr) - 1;
        } catch (NumberFormatException nfe) {
            throw new DyuqueException("Expected integer but received: " + indexStr, nfe);
        }
    }

    void requestStop() {
        executionShouldStop = true;
    }

    boolean isExitRequested() {
        return executionShouldStop;
    }
}
